feat: SLSA provenance for images

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -225,8 +225,12 @@ jobs:
     runs-on: ubuntu-latest
     permissions:
       packages: write
-      id-token: write # OIDC artifact signing
-
+      # provenance
+      id-token: write
+      actions: read
+    env:
+      BUILDER_BINARY: slsa-generator-container-linux-amd64
+      BUILDER_DIR: internal/builders/container
     steps:
     - uses: docker/metadata-action@v4.6.0
       id: meta
@@ -255,10 +259,61 @@ jobs:
         images: ${{ steps.build.outputs.tags }}
         push: true
 
-    # TODO open issue for docker-manifest-action to output digests
+    - name: Generate manifest provenance
+      run: printf "${{ steps.manifest.outputs.images }}" | xargs -d "," -I {} cosign sign --yes {}
+
+    - name: Get manifest digest
+      id: manifest-parsed
+      run: echo $IMAGES | cut -d "," -f1 | sed "s/.*@/digest=/"
+      env:
+        IMAGES: ${{ steps.manifest.outputs.images }}
+
     - uses: sigstore/cosign-installer@v3.1.1
-    - name: Sign manifests
-      run: printf "${{ steps.manifest.outputs.images }}" | xargs -d "," -I {} cosign sign --yes {} # @${{ steps.<build-and-push>.outputs.digest }}
+    - name: Setup provenance builder
+      uses: slsa-framework/slsa-github-generator/.github/actions/generate-builder@v1.7.0
+      with:
+        repository: slsa-framework/slsa-github-generator
+        ref: refs/tags/v1.7.0
+        go-version: 1.20
+        directory: ${{ env.BUILDER_DIR }}
+        binary: ${{ env.BUILDER_BINARY }}
+        compile-builder: false
+        allow-private-repository: false
+
+    # - name: Login
+    #   id: login
+    #   continue-on-error: true
+    #   env:
+    #     UNTRUSTED_IMAGE: ${{ steps.meta.outputs.tags }}
+    #     UNTRUSTED_INPUT_USERNAME: ${{ github.actor }}
+    #     UNTRUSTED_PASSWORD: ${{ github.token }}
+    #   run: |
+    #     set -euo pipefail
+
+    #     # NOTE: Some docker images are of the form <org>/<name>
+    #     # Here we get the first part and check if it has a '.' or ':'
+    #     # character in it to see if it's a domain name.
+    #     # See: https://stackoverflow.com/questions/37861791/how-are-docker-image-names-parsed#37867949
+    #     untrusted_registry="docker.io"
+    #     # NOTE: Do not fail the script if grep does not match.
+    #     maybe_domain=$(echo "${UNTRUSTED_IMAGE}" | cut -f1 -d "/" | { grep -E "\.|:" || true; })
+    #     if [ "${maybe_domain}" != "" ]; then
+    #       untrusted_registry="${maybe_domain}"
+    #     fi
+
+    #     echo "login to ${untrusted_registry}"
+    #     cosign login "${untrusted_registry}" -u "${UNTRUSTED_INPUT_USERNAME}" -p "${UNTRUSTED_PASSWORD}"
+
+    - name: Create and sign provenance
+      env:
+        UNTRUSTED_IMAGE: ${{ steps.meta.outputs.tags }}
+        UNTRUSTED_DIGEST: ${{ steps.manifest-parsed.outputs.digest }}
+        GITHUB_CONTEXT: ${{ toJSON(github) }}
+      # COSIGN_EXPERIMENTAL=1
+      run: |
+        "$GITHUB_WORKSPACE/$BUILDER_BINARY" generate --predicate=predicate.json
+        cosign attest --yes --predicate=predicate.json --type slsaprovenance \
+          "${UNTRUSTED_IMAGE}@${UNTRUSTED_DIGEST}"
 
     - uses: Chizkiyahu/delete-untagged-ghcr-action@v2.0.1
       continue-on-error: true
@@ -267,4 +322,3 @@ jobs:
         token: ${{ secrets.GH_PAT_DELETE_PACKAGES }}
         package_name: ${{ matrix.target }}
         except_untagged_multiplatform: true
-        
